name: yogacharm
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8251629450824112
title: yogacharm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fae0fb'
    - '#f69e9a'
    - '#8b5b69'
    - '#392131'
  brandStrength: 0
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
