title: yogacharm
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5234042
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#000000'
    - '#fae0fb'
    - '#f69e9a'
    - '#8b5b69'
    - '#392131'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: yogacharm
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 1
layout_spectrum: 1
